---
- hosts: webserver
  remote_user: root
  strategy: free
  become: yes
  gather_facts: False
  pre_tasks:
    - name: install requirement tools
      raw: apt install -y python-pip && apt install -y python-setuptools && pip install zip
      changed_when: False

    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False

    - name: install python tools
      apt: pkg={{ item }} state=installed
      with_items:
        - python3-pip
        - python3-dev
        - python3-virtualenv
        - python3-psutil

    - name: instll requirement.txt
      shell: pip3 install -r requirement.txt
      args:
        chdir: /home/







